CREATE DATABASE  IF NOT EXISTS `THANH19`;
CREATE TABLE `THANH19`.`employee` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);